### ISSUE TITLE
Issues with pre-release data collections and catalogs

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/input-data-catalogs#1]
This is a thread for posting issues with data catalogs that are missing or erroneous.

Collections that need review:
- [x] HEMCO/ZHANG_Rn222/v2021-11
- [x] HEMCO/VOLCANO/v2021-09

**Comment by LiamBindle** [comment]
@laestrada told me he was having issues with `HEMCO/ZHANG_Rn222/v2021-11`.

**Comment by laestrada** [comment]
As well as `HEMCO/VOLCANO/v2021-09/`

**Comment by LiamBindle** [comment]
HEMCO/ZHANG_Rn222/v2021-11 and HEMCO/VOLCANO/v2021-09/ should be good to go now. They weren't indexed yet.
