### ISSUE TITLE
14.4.0 catalogs missing from geoschemdata.wustl.edu

### ISSUE THREAD

**Issue by ihough** [geoschem/input-data-catalogs#6]
Not sure if this is the right place to report this, but the 14.4.0 data catalogs are missing from http://geoschemdata.wustl.edu/ExtData/DataCatalogs/14.4.0 (the directory is empty).

**Comment by yantosca** [comment]
Thanks for writing @ihough.  You might need to do the following

```console
$ git checkout main
$ git submodule update --init --recursive
```
That should refresh the repo and you should see the 14.4.0 files there.

Also tagging @yidant

**Comment by ihough** [comment]
Thanks @yantosca! After cloning the [input-data-catalogs repo](https://github.com/geoschem/input-data-catalogs) and updating the submodules I see the 14.4.0 files. FYI the files do not seem to be available for direct download from the [WashU data portal](http://geoschemdata.wustl.edu/).

**Comment by yidant** [comment]
Thanks for reporting this @ihough! The files are now available at WashU portal!

**Comment by yantosca** [comment]
Thanks @ihough and @yidant.  I'll close out this issue now.
